KNOBS = ['client_oc_size',
    'mds_beacon_grace',
    'mds_cache_size',
    'mds_early_reply',
    'mds_enable_op_tracker',
    'mds_memory_optimize',
    'mds_store_backtrace_num',
    'mds_store_mpool_multi',
    'bluefs_alloc_size',
    'bluefs_buffered_io',
    'bluefs_max_prefetch',
    'bluefs_min_flush_size',
    'bluefs_preextend_wal_files',
    'bluefs_sync_write',
    'client_acl_choose_optimization',
    'client_acl_delete_permissions',
    'client_acl_extend_permissions',
    'client_acl_type',
    'client_acl_update',
    'client_acl_visible_permissions',
    'client_agg_delete_ctime',
    'client_agg_filetier',
    'client_agg_max_file_size',
    'client_agg_scan_interval',
    'client_aggfile_delete',
    'client_aggobj_flush_interval',
    'client_aggregate_file_size',
    'client_auto_drop_cap',
    'client_cache_base_size',
    'client_cache_mid',
    'client_cache_size',
    'client_cacher_shrink_ratio',
    'client_calc_rate_interval',
    'client_calc_stripe_ratio',
    'client_cap_fs_restrain',
    'client_cap_monitoring',
    'client_cap_revoke_awake',
    'client_cap_revoke_reset',
    'client_cap_revoking_print',
    'client_caps_nohit',
    'client_change_inst_sync',
    'client_check_InodeValid',
    'client_check_pool_perm',
    'client_clear_dir_complete',
    'client_control_time_busy',
    'client_control_time_tbusy',
    'client_ctime_opts',
    'client_data_consistent',
    'client_oc',
    'client_oc_max_dirty',
    'client_oc_max_dirty_age',
    'client_oc_max_objects',
    'client_oc_size',
    'client_oc_target_dirty',
    'client_readahead_max_bytes',
    'client_readahead_max_periods',
    'client_readahead_min',
    'client_write_opts_switch',
    'fuse_atomic_o_trunc',
    'fuse_big_writes',
    'fuse_disable_pagecache',
    'fuse_multithreaded',
    'fuse_require_active_mds',
    'fuse_syncfs_on_mksnap',
    'fuse_use_invalidate_cb',
    'fuse_use_memory_opts',
    'journaler_allow_split_entries',
    'journaler_batch_interval',
    'journaler_batch_max',
    'journaler_prefetch_periods',
    'journaler_prezero_periods',
    'journaler_write_head_interval',
    'mds_async_inode_map',
    'mds_bal_frag',
    'mds_bal_fragment_control',
    'mds_bal_fragment_interval',
    'mds_bal_fragment_size_again',
    'mds_bal_fragment_size_max',
    'mds_bal_fragment_size_split',
    'mds_bal_idle_threshold',
    'mds_bal_interval',
    'mds_bal_merge_rd',
    'mds_bal_merge_size',
    'mds_bal_merge_wr',
    'mds_bal_replicate_threshold',
    'mds_bal_sample_interval',
    'mds_bal_split_bits',
    'mds_bal_split_rd',
    'mds_bal_split_size',
    'mds_bal_split_wr',
    'mds_bal_target_removal_max',
    'mds_bal_target_removal_min',
    'mds_bal_unreplicate_threshold',
    'mds_beacon_epoch_skip_dne',
    'mds_beacon_grace',
    'mds_beacon_interval',
    'mds_blacklist_interval',
    'mds_cache_max_trim',
    'mds_cache_mid',
    'mds_cache_size',
    'mds_cache_size_base',
    'mds_cap_fs_restrain',
    'mds_cap_tracker_event_count',
    'mds_client_prealloc_inos',
    'mds_client_writeable_range_max_inc_objs',
    'mds_damage_table_max_entries',
    'mds_decay_halflife',
    'mds_detail_track',
    'mds_dir_max_commit_size',
    'mds_early_reply',
    'mds_enable_op_tracker',
    'mds_enforce_unique_name',
    'mds_file_delete_actual_size',
    'mds_filetier_cache_size',
    'mds_filetier_preopen',
    'mds_filetier_reply_file_check',
    'mds_fragment_dir_size_migrator',
    'mds_fragment_failinto_queue',
    'mds_fragment_file_migrator_control',
    'mds_fragment_file_size_migrator',
    'mds_fragment_migrator_control',
    'mds_fragment_size_migrator',
    'mds_fragment_skip_master_rank',
    'mds_fs_filetier',
    'mds_import_caps_for_open',
    'mds_max_file_recover',
    'mds_max_file_size',
    'mds_max_optimized_ops',
    'mds_max_optimized_ops_per_osd',
    'mds_max_purge_delay_rate',
    'mds_max_purge_files',
    'mds_max_purge_ops',
    'mds_max_purge_ops_per_pg',
    'mds_max_scrub_ops_in_progress',
    'mds_max_subtrees',
    'mds_max_xattr_pairs_size',
    'mds_md_readahead',
    'mds_memory_captrim',
    'mds_memory_optimize',
    'mds_metablob_not_check_inline',
    'mds_multimds_snapshot_upgrade',
    'mds_op_complaint_time',
    'mds_op_history_duration',
    'mds_op_history_size',
    'mds_optimized_op_priority',
    'mds_osd_delayed_op',
    'mds_purge_delay_req',
    'mds_quota_early_reply',
    'mds_readdir_way_inodex',
    'mds_reconnect_probe_old_client',
    'mds_recover_max_size',
    'mds_recover_max_size_add',
    'mds_recover_max_size_del',
    'mds_recover_not_check_time',
    'mds_replay_interval',
    'mds_reset_interval',
    'mds_reset_session_back',
    'mds_reset_session_degraded',
    'mds_scatter_nudge_interval',
    'mds_session_auto_evict',
    'mds_session_autoclose',
    'mds_session_open_reack',
    'mds_session_stale_not_recover',
    'mds_sessionmap_keys_per_op',
    'mds_snap_max_uid',
    'mds_snap_min_uid',
    'mds_snap_rstat',
    'mds_standby_for_fscid',
    'mds_standby_for_name',
    'mds_standby_for_rank',
    'mds_standby_replay',
    'mds_stop_subtree',
    'mds_store_backtrace_not_check_old',
    'mds_store_backtrace_num',
    'mds_store_mpool_multi',
    'mds_store_mpool_new',
    'mds_switch_fast_try',
    'mds_switch_fast_try_multi',
    'mds_tick_interval',
    'mds_trim_bot_interval',
    'mds_trim_tid',
    'mds_truncate_mode',
    'mds_weak_consistency',
    'multi_mds_balance',
    'worm_cap_ttl',
    'worm_enable_time'
]
KNOB_DETAILS = { 'client_oc_size': ['OPT_U64', [4096.0, 4294967296.0, 2147483648.0]],
    'mds_beacon_grace': ['OPT_FLOAT', [10.0, 120.0, 60.0]],
    'mds_cache_size': ['OPT_INT', [50000.0, 10000000.0, 1000000.0]],
    'mds_early_reply': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_enable_op_tracker': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_memory_optimize': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_store_backtrace_num': ['OPT_U32', [1.0, 10240.0, 500.0]],
    'mds_store_mpool_multi': ['OPT_BOOL', ['false', 'true', 1]],
    'bluefs_alloc_size': ['OPT_U64', [4096.0, 4194304.0, 1048576.0]],
    'bluefs_buffered_io': ['OPT_BOOL', ['false', 'true', 0]],
    'bluefs_max_prefetch': ['OPT_U64', [4096.0, 4194304.0, 1048576.0]],
    'bluefs_min_flush_size': ['OPT_U64', [2048.0, 2097152.0, 524288.0]],
    'bluefs_preextend_wal_files': ['OPT_BOOL', ['false', 'true', 0]],
    'bluefs_sync_write': ['OPT_BOOL', ['false', 'true', 0]],
    'client_acl_choose_optimization': ['OPT_BOOL', ['false', 'true', 1]],
    'client_acl_delete_permissions': ['OPT_BOOL', ['false', 'true', 0]],
    'client_acl_extend_permissions': ['OPT_BOOL', ['false', 'true', 0]],
    'client_acl_type': ['OPT_STR', ['none', 'posix_acl', 'posix_acl']],
    'client_acl_update': ['OPT_BOOL', ['false', 'true', 0]],
    'client_acl_visible_permissions': ['OPT_BOOL', ['false', 'true', 0]],
    'client_agg_delete_ctime': ['OPT_U32', [60.0, 3600.0, 600.0]],
    'client_agg_filetier': ['OPT_BOOL', ['false', 'true', 0]],
    'client_agg_max_file_size': ['OPT_U64', [512.0, 4194304.0, 524288.0]],
    'client_agg_scan_interval': ['OPT_DOUBLE', [60.0, 7200.0, 3600.0]],
    'client_aggfile_delete': ['OPT_INT', ['false', 'true', 0]],
    'client_aggobj_flush_interval': ['OPT_U32', [1.0, 60.0, 5.0]],
    'client_aggregate_file_size': ['OPT_U64', [524288.0, 4294967296.0, 536870912.0]],
    'client_auto_drop_cap': ['OPT_BOOL', ['false', 'true', 1]],
    'client_cache_base_size': ['OPT_INT', [4096.0, 1310720.0, 327680.0]],
    'client_cache_mid': ['OPT_FLOAT', [0.1, 5.0, 0.75]],
    'client_cache_size': ['OPT_INT', [4096.0, 1310720.0, 32768.0]],
    'client_cacher_shrink_ratio': ['OPT_DOUBLE', [0.1, 10.0, 1.0]],
    'client_calc_rate_interval': ['OPT_DOUBLE', [0.1, 20.0, 4.0]],
    'client_calc_stripe_ratio': ['OPT_U32', [1.0, 100.0, 10.0]],
    'client_cap_fs_restrain': ['OPT_BOOL', ['false', 'true', 0]],
    'client_cap_monitoring': ['OPT_BOOL', ['false', 'true', 0]],
    'client_cap_revoke_awake': ['OPT_BOOL', ['false', 'true', 1]],
    'client_cap_revoke_reset': ['OPT_BOOL', ['false', 'true', 1]],
    'client_cap_revoking_print': ['OPT_BOOL', ['false', 'true', 0]],
    'client_caps_nohit': ['OPT_U32', [1.0, 1024.0, 200.0]],
    'client_change_inst_sync': ['OPT_BOOL', ['false', 'true', 1]],
    'client_check_InodeValid': ['OPT_BOOL', ['false', 'true', 1]],
    'client_check_pool_perm': ['OPT_BOOL', ['false', 'true', 1]],
    'client_clear_dir_complete': ['OPT_BOOL', ['false', 'true', 1]],
    'client_control_time_busy': ['OPT_INT', [1.0, 60.0, 5.0]],
    'client_control_time_tbusy': ['OPT_INT', [1.0, 120.0, 20.0]],
    'client_ctime_opts': ['OPT_BOOL', ['false', 'true', 0]],
    'client_data_consistent': ['OPT_BOOL', ['false', 'true', 1]],
    'client_oc': ['OPT_BOOL', ['false', 'true', 1]],
    'client_oc_max_dirty': ['OPT_U64', [4096.0, 4294967296.0, 2147483648.0]],
    'client_oc_max_dirty_age': ['OPT_DOUBLE', [1.0, 60.0, 5.0]],
    'client_oc_max_objects': ['OPT_INT', [1.0, 4096.0, 1000.0]],
    'client_oc_size': ['OPT_U64', [4096.0, 4294967296.0, 2147483648.0]],
    'client_oc_target_dirty': ['OPT_U64', [2048.0, 2147483648.0, 1073741824.0]],
    'client_readahead_max_bytes': ['OPT_LONGLONG', [0.0, 60.0, 0.0]],
    'client_readahead_max_periods': ['OPT_LONGLONG', [1.0, 60.0, 4.0]],
    'client_readahead_min': ['OPT_LONGLONG', [1024.0, 524288.0, 131072.0]],
    'client_write_opts_switch': ['OPT_BOOL', ['false', 'true', 0]],
    'fuse_atomic_o_trunc': ['OPT_BOOL', ['false', 'true', 1]],
    'fuse_big_writes': ['OPT_BOOL', ['false', 'true', 1]],
    'fuse_disable_pagecache': ['OPT_BOOL', ['false', 'true', 0]],
    'fuse_multithreaded': ['OPT_BOOL', ['false', 'true', 1]],
    'fuse_require_active_mds': ['OPT_BOOL', ['false', 'true', 1]],
    'fuse_syncfs_on_mksnap': ['OPT_BOOL', ['false', 'true', 1]],
    'fuse_use_invalidate_cb': ['OPT_BOOL', ['false', 'true', 1]],
    'fuse_use_memory_opts': ['OPT_BOOL', ['false', 'true', 1]],
    'journaler_allow_split_entries': ['OPT_BOOL', ['false', 'true', 1]],
    'journaler_batch_interval': ['OPT_DOUBLE', [0.0001, 0.1, 0.001]],
    'journaler_batch_max': ['OPT_U64', [0.0, 1024.0, 0.0]],
    'journaler_prefetch_periods': ['OPT_INT', [1.0, 128.0, 10.0]],
    'journaler_prezero_periods': ['OPT_INT', [1.0, 60.0, 5.0]],
    'journaler_write_head_interval': ['OPT_INT', [1.0, 60.0, 15.0]],
    'mds_async_inode_map': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_bal_frag': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_bal_fragment_control': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_bal_fragment_interval': ['OPT_INT', [1.0, 60.0, 5.0]],
    'mds_bal_fragment_size_again': ['OPT_INT', [1.0, 60.0, 3.0]],
    'mds_bal_fragment_size_max': ['OPT_INT', [10000.0, 10000000.0, 10000000.0]],
    'mds_bal_fragment_size_split': ['OPT_INT', [1000.0, 40000.0, 10000.0]],
    'mds_bal_idle_threshold': ['OPT_FLOAT', [0.0, 1024.0, 0.0]],
    'mds_bal_interval': ['OPT_INT', [1.0, 60.0, 10.0]],
    'mds_bal_merge_rd': ['OPT_FLOAT', [1.0, 4000.0, 1000.0]],
    'mds_bal_merge_size': ['OPT_INT', [1.0, 500.0, 50.0]],
    'mds_bal_merge_wr': ['OPT_FLOAT', [1.0, 4096.0, 1000.0]],
    'mds_bal_replicate_threshold': ['OPT_FLOAT', [1024.0, 32000.0, 8000.0]],
    'mds_bal_sample_interval': ['OPT_FLOAT', [1.0, 60.0, 3.0]],
    'mds_bal_split_bits': ['OPT_INT', [1.0, 60.0, 3.0]],
    'mds_bal_split_rd': ['OPT_FLOAT', [2500.0, 60000.0, 25000.0]],
    'mds_bal_split_size': ['OPT_INT', [1000.0, 40000.0, 10000.0]],
    'mds_bal_split_wr': ['OPT_FLOAT', [1000.0, 40000.0, 10000.0]],
    'mds_bal_target_removal_max': ['OPT_INT', [1.0, 100.0, 10.0]],
    'mds_bal_target_removal_min': ['OPT_INT', [1.0, 60.0, 5.0]],
    'mds_bal_unreplicate_threshold': ['OPT_FLOAT', [0.0, 60.0, 0.0]],
    'mds_beacon_epoch_skip_dne': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_beacon_grace': ['OPT_FLOAT', [1.0, 240.0, 60.0]],
    'mds_beacon_interval': ['OPT_FLOAT', [1.0, 60.0, 4.0]],
    'mds_blacklist_interval': ['OPT_FLOAT', [24.0, 5760.0, 1440.0]],
    'mds_cache_max_trim': ['OPT_U64', [1000.0, 800000.0, 100000.0]],
    'mds_cache_mid': ['OPT_FLOAT', [0.1, 10.0, 0.7]],
    'mds_cache_size': ['OPT_INT', [100000.0, 8000000.0, 1000000.0]],
    'mds_cache_size_base': ['OPT_INT', [200000.0, 8000000.0, 2000000.0]],
    'mds_cap_fs_restrain': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_cap_tracker_event_count': ['OPT_INT', [1.0, 100.0, 10.0]],
    'mds_client_prealloc_inos': ['OPT_INT', [500.0, 50000.0, 5000.0]],
    'mds_client_writeable_range_max_inc_objs': ['OPT_U32', [128.0, 4096.0, 1024.0]],
    'mds_damage_table_max_entries': ['OPT_INT', [1024.0, 50000.0, 10000.0]],
    'mds_decay_halflife': ['OPT_FLOAT', [1.0, 100.0, 5.0]],
    'mds_detail_track': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_dir_max_commit_size': ['OPT_INT', [1.0, 100.0, 10.0]],
    'mds_early_reply': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_enable_op_tracker': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_enforce_unique_name': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_file_delete_actual_size': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_filetier_cache_size': ['OPT_INT', [1000.0, 800000.0, 100000.0]],
    'mds_filetier_preopen': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_filetier_reply_file_check': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_fragment_dir_size_migrator': ['OPT_INT', [10.0, 3000.0, 300.0]],
    'mds_fragment_failinto_queue': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_fragment_file_migrator_control': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_fragment_file_size_migrator': ['OPT_INT', [500.0, 50000.0, 5000.0]],
    'mds_fragment_migrator_control': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_fragment_size_migrator': ['OPT_INT', [1.0, 100.0, 3.0]],
    'mds_fragment_skip_master_rank': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_fs_filetier': ['OPT_U32', [0.0, 100.0, 0.0]],
    'mds_import_caps_for_open': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_max_file_recover': ['OPT_U32', [1.0, 1024.0, 32.0]],
    'mds_max_file_size': ['OPT_U64', [140737000000000.0, 180737488355328.0, 140737488355328.0]],
    'mds_max_optimized_ops': ['OPT_U64', [2048.0, 2097152.0, 524288.0]],
    'mds_max_optimized_ops_per_osd': ['OPT_U32', [0.0, 1024.0, 0.0]],
    'mds_max_purge_delay_rate': ['OPT_FLOAT', [0.1, 10.0, 0.3]],
    'mds_max_purge_files': ['OPT_U32', [1.0, 512.0, 64.0]],
    'mds_max_purge_ops': ['OPT_U32', [512.0, 32768.0, 8192.0]],
    'mds_max_purge_ops_per_pg': ['OPT_FLOAT', [0.1, 10.0, 0.5]],
    'mds_max_scrub_ops_in_progress': ['OPT_INT', [1.0, 100.0, 5.0]],
    'mds_max_subtrees': ['OPT_U32', [1.0, 4096.0, 1000.0]],
    'mds_max_xattr_pairs_size': ['OPT_U32', [4096.0, 262144.0, 65536.0]],
    'mds_md_readahead': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_memory_captrim': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_memory_optimize': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_metablob_not_check_inline': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_multimds_snapshot_upgrade': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_op_complaint_time': ['OPT_FLOAT', [1.0, 300.0, 30.0]],
    'mds_op_history_duration': ['OPT_U32', [60.0, 14400.0, 3600.0]],
    'mds_op_history_size': ['OPT_U32', [1.0, 200.0, 20.0]],
    'mds_optimized_op_priority': ['OPT_U32', [1.0, 630.0, 63.0]],
    'mds_osd_delayed_op': ['OPT_FLOAT', [1.0, 30.0, 3.0]],
    'mds_purge_delay_req': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_quota_early_reply': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_readdir_way_inodex': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_reconnect_probe_old_client': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_recover_max_size': ['OPT_U64', [0.0, 1024.0, 0.0]],
    'mds_recover_max_size_add': ['OPT_U64', [1000000000.0, 4294967296.0, 1073741824.0]],
    'mds_recover_max_size_del': ['OPT_U64', [0.0, 1024.0, 0.0]],
    'mds_recover_not_check_time': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_replay_interval': ['OPT_FLOAT', [0.1, 50.0, 1.0]],
    'mds_reset_interval': ['OPT_FLOAT', [0.5, 30.0, 3.0]],
    'mds_reset_session_back': ['OPT_U32', [5.0, 60.0, 20.0]],
    'mds_reset_session_degraded': ['OPT_INT', [2.0, 32.0, 8.0]],
    'mds_scatter_nudge_interval': ['OPT_FLOAT', [1.0, 60.0, 5.0]],
    'mds_session_auto_evict': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_session_autoclose': ['OPT_FLOAT', [30.0, 900.0, 300.0]],
    'mds_session_open_reack': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_session_stale_not_recover': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_sessionmap_keys_per_op': ['OPT_U32', [128.0, 4096.0, 1024.0]],
    'mds_snap_max_uid': ['OPT_U32', [128.0, 262144.0, 65536.0]],
    'mds_snap_min_uid': ['OPT_U32', [0.0, 1024.0, 0.0]],
    'mds_snap_rstat': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_standby_for_fscid': ['OPT_INT', [-10.0, 10.0, -1.0]],
    'mds_standby_for_name': ['OPT_STR', ['none', 'posix_acl', 'posix_acl']],
    'mds_standby_for_rank': ['OPT_INT', [-10.0, 10.0, -1.0]],
    'mds_standby_replay': ['OPT_BOOL', ['false', 'true', 0]],
    'mds_stop_subtree': ['OPT_U32', [1.0, 500.0, 50.0]],
    'mds_store_backtrace_not_check_old': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_store_backtrace_num': ['OPT_U32', [50.0, 5000.0, 500.0]],
    'mds_store_mpool_multi': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_store_mpool_new': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_switch_fast_try': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_switch_fast_try_multi': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_tick_interval': ['OPT_FLOAT', [1.0, 60.0, 5.0]],
    'mds_trim_bot_interval': ['OPT_INT', [1.0, 100.0, 10.0]],
    'mds_trim_tid': ['OPT_BOOL', ['false', 'true', 1]],
    'mds_truncate_mode': ['OPT_INT', [0.0, 100.0, 0.0]],
    'mds_weak_consistency': ['OPT_BOOL', ['false', 'true', 0]],
    'multi_mds_balance': ['OPT_BOOL', ['false', 'true', 1]],
    'worm_cap_ttl': ['OPT_INT', [0.0, 100.0, 0.0]],
    'worm_enable_time': ['OPT_INT', [0.0, 100.0, 0.0]]
}

def get_init_knobs():
    knobs = {}
    for name, value in KNOB_DETAILS.items():
        knob_value = value[1]
        knobs[name] = knob_value[-1]
    return knobs


def gen_continuous(action):
    knobs = {}
    for idx in xrange(len(KNOBS)):
        name = KNOBS[idx]
        value = KNOB_DETAILS[name]

        knob_type = value[0]
        knob_value = value[1]
        min_value = knob_value[0]

        if knob_type == 'OPT_INT' or knob_type == 'OPT_LONGLONG' or knob_type == 'OPT_U32' or knob_type == 'OPT_U64':
            max_val = knob_value[1]
            eval_value = int(max_val * action[idx])
            # eval_value is the bigger one between min_value and (max_val * action[idx])
            eval_value = max(eval_value, min_value)
        elif knob_type == 'OPT_FLOAT' or knob_type == 'OPT_DOUBLE':
            max_val = knob_value[1]
            eval_value = max_val * action[idx]
            # eval_value is the bigger one between min_value and (max_val * action[idx])
            eval_value = max(eval_value, min_value)
        elif knob_type == 'OPT_BOOL':
            if action[idx] <= 0.5:
                eval_value = True
            else:
                eval_value = False
        elif knob_type == 'OPT_STR':
            if action[idx] <= 0.5:
                eval_value = 'posix_acl'
            else:
                eval_value = 'none'
        knobs[name] = eval_value
    return knobs

